blank_issues_enabled: false
contact_links:
  - name: 💬 Contacto Directo WhatsApp PolyLab
    url: https://wa.me/526683956301?text=Hola%20Ramsses,%20contacto%20sobre%20Oficios%20Ahome
    about: Escribe directamente al creador de la plataforma para dudas o colaboraciones.
